name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          sudo apt-get update
          sudo apt-get install aria2 cabextract wimtools chntpw genisoimage -y
          chmod +x uup_download_linux.sh
          "./uup_download_linux.sh"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ISO
          path: |
            *.ISO
